name: BuildAndPushImageOnHarbor 
on: 
  workflow_call:
    inputs:
      project: 
        required: true
        type: string
      container:     
        required: true
        type: string       
      image-name-file: 
        required: false
        type: string 
        default: "image"
          
jobs: 
  reusable_workflow_job: 
    runs-on: ubuntu-latest 
    steps:              
    - name: vars
      run: |
        echo ${{ secrets.TOKEN }}
        echo ${{ inputs.project }}
        echo ${{ inputs.container }}
        echo ${{ inputs.image-name-file }}
        
    - name: Clone Repository 
      run: | 
        git clone https://${{ secrets.TOKEN }}@github.com/jennermand/picluster.git
 
    - name: UpdateRefFile 
      run: | 
        yq -i '.angular-app.image.repository = "ginkartoteket/ginkartoteket" | .angular-app.image.tag = "latest"' ./picluster/apps/${{ inputs.project }}/values.yaml 
         
    - name: Push to Repo 
      run: | 
        git config --global user.name "autobot@karsoe.dk" 
        git config --global user.email "autobot@karsoe.dk" 
        cd ./picluster 
        git add . 
        git commit -m "Updated by GitHub Actions" 
        git push https://${{ secrets.TOKEN }}@github.com/jennermand/picluster.git --all 
